# Generated by Django 4.2.20 on 2025-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
