# Generated by Django 4.2.20 on 2025-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_billing_address_member_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='old_cart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
