# Generated by Django 4.2.20 on 2025-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='location',
            new_name='adress1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='member',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='Slovensko', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='zipcode',
            field=models.CharField(default='02951', max_length=255),
            preserve_default=False,
        ),
    ]
