# Generated by Django 4.2.20 on 2025-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.RemoveField(
            model_name='member',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
