# Generated by Django 5.1.6 on 2025-03-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member',
            field=models.ManyToManyField(related_name='orders', to='member.member'),
        ),
    ]
