# Generated by Django 4.2.20 on 2025-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='product',
            new_name='products',
        ),
    ]
