# Generated by Django 4.2.20 on 2025-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_full_name',
            new_name='shipping_first_name',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_last_name',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
