# Generated by Django 4.2.20 on 2025-04-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_user'),
        ('order', '0015_rename_full_name_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='member.member'),
        ),
    ]
