# Generated by Django 4.2.20 on 2025-04-15 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0016_alter_shippingaddress_shipping_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
