# Generated by Django 4.2.20 on 2025-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_shippingaddress_shipping_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shipping_label',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
